### ISSUE TITLE
MP4 format

### ISSUE THREAD

**Issue by Defselom** [Pauloo27/tiktok-live#8]
Good morning. I have been using your program every time and it is very convenient for me. But I have trouble with the flv format. please can you implement a mp4 format?

**Comment by Pauloo27** [comment]
Good morning.

I've just updated the project, now it's going to download a mp4, can you please test it? You will need to install ffmpeg
(https://ffmpeg.org/)

**Comment by Defselom** [comment]
I just tested and it works great!
I love it so much. 

I would like to know if it would be possible to implement also the comments of the live in the recording.
